# Generated by Django 4.0.4 on 2022-04-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tank_capacity', models.PositiveIntegerField(verbose_name='Fuel Tank Capacity')),
                ('consumption', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plane')),
            ],
        ),
    ]
